version: "2.2"

services:
  # Apache Zookeeper instance
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.5.7
    volumes:
      - ./storage/zk/data:/data
      - ./storage/zk/trxn:/datalog
    environment:
      - ZOO_MY_ID=1

  # Apache BookKeeper instance
  # apache/bookkeeper:4.9.2
  bookie:
    container_name: bookie
    hostname: bookie
    image: apache/bookkeeper:4.9.2
    volumes:
      - ./storage/bookie:/data/bookkeeper
      - ./init-bookie.sh:/init-bookie.sh
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
    entrypoint:
      - /bin/bash
      - /init-bookie.sh
    environment:
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers
      - BK_httpServerEnabled=true
      - BK_httpServerPort=8080
      - BK_useHostNameAsBookieID=true
      - BK_useShortHostName=true

  # Apache Pulsar cluster
  # apachepulsar/pulsar-all:2.5.1
  # apachepulsar/pulsar-dashboard:2.5.1
  pulsar:
    container_name: pulsar
    hostname: pulsar
    image: apachepulsar/pulsar-all:2.5.1
    ports:
      - "6650:6650"
      - "8081:8081"
    depends_on:
      - zookeeper
      - bookie
    volumes:
      - ./storage/pulsar:/pulsar_data
      - ./init-pulsar.sh:/init-pulsar.sh
    entrypoint:
      - /bin/bash
      - /init-pulsar.sh
    environment:
      # initialization settings
      - PULSAR_BROKER_CONF=/pulsar_data/broker.conf
      - PULSAR_CONFIG_webServiceEndpoint=http://pulsar:8081
      - PULSAR_CONFIG_brokerServiceEndpoint=pulsar://pulsar:6650
      # pulsar settings
      - PULSAR_PREFIX_advertisedAddress=localhost
      - PULSAR_PREFIX_clusterName=pulsar
      - PULSAR_PREFIX_zookeeperServers=zookeeper:2181
      - PULSAR_PREFIX_configurationStoreServers=zookeeper:2181
      # single bookie configuration
      - PULSAR_PREFIX_managedLedgerDefaultEnsembleSize=1
      - PULSAR_PREFIX_managedLedgerDefaultWriteQuorum=1
      - PULSAR_PREFIX_managedLedgerDefaultAckQuorum=1
