version: "2"

services:
  # Apache Zookeeper node
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.6.1
    volumes:
      - ./storage/zk/data:/data
      - ./storage/zk/trxn:/datalog
    environment:
      - ZOO_MY_ID=1

  # Apache BookKeeper bookie node
  bookie:
    container_name: bookie
    hostname: bookie
    image: apache/bookkeeper:4.14.1
    volumes:
      - ./storage/bookie:/data/bookkeeper
      - ./init-bookie.sh:/init-bookie.sh
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
    entrypoint:
      - /bin/bash
      - /init-bookie.sh
    environment:
      - BK_zkServers=zookeeper:2181
      - BK_zkLedgersRootPath=/ledgers
      - BK_httpServerEnabled=true
      - BK_httpServerPort=8081
      - BK_useHostNameAsBookieID=true
      - BK_useShortHostName=true

  # Apache Pulsar broker node
  pulsar:
    container_name: pulsar
    hostname: pulsar
    image: apachepulsar/pulsar-all:2.8.0
    ports:
      - "6650:6650"
      - "8080:8080"
    depends_on:
      - zookeeper
      - bookie
    volumes:
      - ./storage/pulsar:/pulsar_data
      - ./init-pulsar.sh:/init-pulsar.sh
    entrypoint:
      - /bin/bash
      - /init-pulsar.sh
    environment:
      # cluster initialization settings
      - PULSAR_BROKER_CONF=/pulsar_data/broker.conf
      # ports
      - PULSAR_PREFIX_webServicePort=8080
      - PULSAR_PREFIX_brokerServicePort=6650
      - PULSAR_PREFIX_clusterName=pulsar
      - PULSAR_PREFIX_advertisedAddress=127.0.0.1
      - PULSAR_PREFIX_zookeeperServers=zookeeper:2181
      - PULSAR_PREFIX_configurationStoreServers=zookeeper:2181
      # bookie configuration (single node quorum/ack settings)
      - PULSAR_PREFIX_managedLedgerDefaultEnsembleSize=1
      - PULSAR_PREFIX_managedLedgerDefaultWriteQuorum=1
      - PULSAR_PREFIX_managedLedgerDefaultAckQuorum=1
      # CLI configuration
      - PULSAR_PREFIX_webServiceUrl=http://localhost:8080
